language: node_js
node_js:
  - "6"
cache:
  yarn: true
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - cp src/config/constants.secrets.js.example src/config/constants.secrets.js
script:
  - yarn run build
  - yarn run test
  - yarn run lint
